matrix:
  include:
    - addons:
        firefox: latest
      language: node_js
      node_js: 4
      install:
        - npm install
      before_script:
        - 'export DISPLAY=:99.0'
        - 'sh -e /etc/init.d/xvfb start'
        - sleep 3
      script:
        - npm test
    - language: python
      python: 2.7
      install:
        - pip install tox
      script:
        - tox -e yamllint
