addons:
  firefox: latest
language: node_js
node_js:
  - '4'
python:
  - "2.7"
install:
  - npm install
  - pip install --user tox
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3
script:
  - npm test
  - tox -e yamllint
